sha-el/sha-el-design

- src/components/Input/Input.tsx
- src/components/Input/TextArea.stories.tsx
- src/components/Input/Textarea.tsx
- src/components/Input/style.tsx
- Add dark theme variant for TextArea
- Add Label props for TextArea
- Add TextArea in the storybook
- Replace TextArea style with Input style
- Change TextArea to Functional Component
#5
> :zap: Add dark theme variant for Textarea

- package.json
- yarn.lock
> :fire: Move `react`, `react-icons` and `react-dom` to peer dependencies.

- README.md
- src/components/AutoComplete/AutoComplete.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/style.tsx
- src/components/Page/Page.stories.tsx
- src/components/Tag/Tag.stories.tsx
- src/components/Tag/Tag.tsx
* Add `size` prop for Tag.
* Update label border styling for `Input`.
* Use `size=small` in Tag@Autocomplete.
> :fire: Basic design fixes

- src/components/Card/Card.stories.tsx
- src/components/Text/Text.stories.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.ts
- src/helpers/text.ts
- src/helpers/topography.css.ts
- src/index.ts
Text component for styling the text.
**Props**:
- **variant** : 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p'
- **italicize**: boolean
- **bold**: boolean
- **fontFamily**: 'mono' | 'cursive' | 'normal' | string
- **fontSize**: number
- **padding**: string
- **margin**: string
- **color**: keyof Theme | string
- **underline**: boolean
- **strikeThrough**: boolean
- **style**: React.CSSProperties
Issue: #10
> :sparkles: Add Text Component

- src/components/AutoComplete/AutoComplete.tsx
Change Popover style from `inline-block` to `block`
> Fix Autocomplete width

- src/components/Card/Card.tsx
- src/helpers/elevations.ts
Elevation props inspired by Material UI. Elevation prop values ranging from 1-24.
- With elevation=5
- With elevation=15
- With elevation=24
> Add elevation prop for Card component

- src/components/Text/Text.stories.tsx
- src/components/Text/Text.tsx
- src/helpers/text.ts
*NOTE:* Will be a breaking change.
> :zap: [Text] Add `fontWeight` prop.

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- src/components/Text/Text.stories.tsx
- src/helpers/color.ts
* Move button loading color to helpers/colors.
* Add story for outline buttons.
> Add `outline` prop to `Button`.

- .github/workflows/release.yml
- src/components/AutoComplete/AutoComplete.stories.tsx
- src/components/AutoComplete/AutoComplete.tsx
- src/components/Button/Button.tsx
- src/components/Card/CardHeader.tsx
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/Input.stories.tsx
- src/components/Input/style.tsx
- src/components/Menu/MenuItem.tsx
- src/components/Menu/MenuItemGroup.tsx
- src/components/Modal/Modal.tsx
- src/components/Popover/Popover.tsx
- src/components/Table/FlexTable.tsx
- src/components/Table/style.ts
- src/helpers/color.ts
- src/index.ts
* **Autocomplete** add disabled prop.
* Fix **Menu** active prop not working.
* **Modal** with border radius 2px.
* **Button** decrease padding when flat.
* **FlexTable** expose row's index to FlexColumns.
* Row style exposed from **FlexTable**.
* **Flextable** on row click.
* Fix **AutoComplete** dropdown width.
* Fix Multi **Autocomplete** always showing X(Close Button).
* Fix **Autocomplete** clearable button triggering form submit.
> Minor design and usage fix.

- __tests__/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/style.ts
**Replace typestyle with jss in badge**
**Move badge style function to separate file**
**Add badge test case** 
#39 
#40 
To test badge 
> Badge test case

- __tests__/components/Breadcrumb/Breadcrumb.spec.tsx
- src/components/Breadcrumb/Breadcrumb.tsx
- src/components/Breadcrumb/style.ts
- src/components/Button/ButtonGroup.tsx
**Replace typestyle with jss in breadcrumb & buttonGroup**
**Move breadcrumb style function to separate file**
**Add test case for breadcrumb**
#39 
#40 
To test breadcrumb
> Breadcrumb test case

- __tests__/components/Tag/Tag.spec.tsx
- src/components/Tag/Tag.tsx
- src/components/Tag/style.ts
**Replace typestyle with jss in tag**
**Move tag style function to separate file**
**Add tag test case**
#39 
#40 
To test tag
> Tag test case

- __tests__/components/CheckBox/CheckBox.spec.tsx
- src/components/CheckBox/CheckBox.tsx
- src/components/CheckBox/style.ts
**Replace typestyle with jss in checkbox**
**Move checkbox style function to separate file**
**Add checkbox test case**
#39 
#40 
To test checkbox
> CheckBox test case

- __tests__/components/Input/input.spec.tsx
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/style.ts
**Replace typestyle with jss**
**Move base baseInputComponent style function to new file**
**Change in use of class syntax from '.class' to '&  .class'**
**Minor fix in input hover effect**
**Input test case**
#39 
#40 
To test input
> Input test case

- __tests__/components/Input/input.spec.tsx
- __tests__/components/Stepper/Stepper.spec.tsx
- __tests__/setup.js
- jest.config.js
- package.json
- src/components/AutoComplete/AutoComplete.tsx
- src/components/Carousel/Carousel.stories.tsx
- src/components/Carousel/Carousel.tsx
- src/components/Grid/Row.tsx
- src/components/Grid/style.ts
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/style.ts
- src/components/List/CollapsibleList.tsx
- src/components/Page/Page.stories.tsx
- src/components/Stepper/Stepper.stories.tsx
- src/components/Stepper/Stepper.tsx
- src/components/Stepper/index.tsx
- src/components/Stepper/style.ts
- src/components/Theme/Theme.tsx
- src/index.ts
- yarn.lock
Stepper component
* #26 
* Stepper can be used to create form wizards.
* Go over all the following points, and put an `x` in all the boxes that apply.
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
> Add stepper component.

- __tests__/components/Badge/Badge.spec.tsx
Add react testing library
Remove other testing library
#39 
Add test case
> Change badge testing library

- __tests__/components/Breadcrumb/Breadcrumb.spec.tsx
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/style.ts
** Add react testing library
** Remove other library
** Fix no hover on components without label
** Fix error message border color
** Fix error message margin
#39 
Add test case
> Change breadcrumb testing lib & input style fix

- __tests__/components/Button/ButtonGroup.spec.tsx
Test case for button group
#39 
Add test case
> Add test for button group

- __tests__/components/CheckBox/CheckBox.spec.tsx
Test case for button group
#39 
Add test case
> Add test for checkbox

- __tests__/components/Tag/Tag.spec.tsx
Test case for tag
#39 
Add test case
> Add onClick test for tag

- __tests__/components/Tag/Tag.spec.tsx
- __tests__/components/Text/Text.spec.tsx
Improve text coverage
#39 
Add test case
> Improve test coverage of text

- __tests__/components/Divider/Divider.spec.tsx
Test case for divider
#39 
Add test case
> Add test for divider

- __tests__/components/AutoComplete/AutoComplete.spec.tsx
- __tests__/components/Input/input.spec.tsx
- src/components/AutoComplete/AutoComplete.stories.tsx
- src/components/AutoComplete/AutoComplete.tsx
- src/components/DatePicker/TimePicker.tsx
- src/components/Input/BaseInputComponent.tsx
- src/components/Input/Input.tsx
- src/components/Input/Textarea.tsx
- src/components/Input/style.ts
- src/components/Radio/RadioButton.tsx
- src/components/Upload/Upload.tsx
> Use forward ref for Input

- src/components/AutoComplete/AutoComplete.tsx
- src/components/Button/Button.tsx
- src/components/Button/style.ts
- src/components/DatePicker/TimePicker.tsx
- src/components/DatePicker/style.ts
- src/components/Layout/style.ts
- src/components/Table/style.ts
- src/helpers/color.ts
* 7bd3abb Minor fixes
* f5ded0a :facepalm: Add background to time picker popup.
* f248c8f Add button focus style.
* fd55857 :fire: Add type="button" as default props ion Button.
> Minor design fix

- __tests__/components/Radio/Radio.spec.tsx
- __tests__/components/Radio/RadioButton.spec.tsx
- __tests__/components/Radio/RadioGroup.spec.tsx
- src/components/Radio/Radio.tsx
- src/components/Radio/RadioButton.tsx
- src/components/Radio/style.ts
- src/helpers/style.ts
* Add test case for radio component.
* Fix Radio Button with group issue where it doesn't remove styles.
* Few minor changes in Radio and Radio Button.
#39 
For code coverage.
> Test cases for radio component.

- __tests__/components/Progress/Progress.spec.tsx
- src/components/Progress/Progress.tsx
Add test cases for progress component
#39 
* For 100% code coverage.
> Test cases for Progress component

- __tests__/components/Timeline/Timeline.spec.tsx
- src/components/Timeline/Timeline.stories.tsx
- src/components/Timeline/Timeline.tsx
- src/components/Timeline/style.ts
* Add test cases for timeline component.
*  Fix single timeline style.
*  Add single timeline to storybook.
#39 
* For 100% code coverage.
> Test cases for Timeline Component

- __tests__/components/Calendar/Calendar.spec.tsx
- src/components/Calendar/Calendar.tsx
Add test for calendar component
#39 
Also fixes #74 
* For coverage.
> Test cases for Calendar

- __tests__/components/Modal/Modal.spec.tsx
- src/components/Modal/Modal.tsx
Add test case for the modal component.
#39 
For 100% test coverage.
> 🧪 Test cases for Modal

- __tests__/components/Collapse/Collapse.spec.tsx
Add test case for the collapse component.
#39 
For 100% test coverage.
> 🧪 Test case for Collapse

- __tests__/components/Drawer/Drawer.spec.tsx
- src/components/Drawer/Drawer.stories.tsx
- src/components/Drawer/Drawer.tsx
- src/components/Drawer/style.ts
Add test case for the drawer component.
#39 
For test coverage.
> 🧪 Test case for Drawer

- __tests__/components/Portal/Portal.spec.tsx
> :fire: Fix portal test

- src/components/Layout/Layout.stories.tsx
- src/components/Layout/SidePanel.tsx
- src/components/Layout/style.ts
- src/components/Page/Page.stories.tsx
- src/components/Page/Page.tsx
- src/components/Page/style.ts
- src/components/Tooltip/Tooltip.tsx
* Add padding in Page header.
* Add Delay prop in tooltip.
* Add prop to hide resizer in Sidepanel.
> Change page and layout styling

- __tests__/components/Progress/Progress.spec.tsx
- __tests__/components/Switch/Switch.spec.tsx
- src/components/Progress/Progress.tsx
- src/components/Progress/style.ts
- src/components/Switch/Switch.stories.tsx
- src/components/Switch/Switch.tsx
- src/components/Switch/index.ts
- src/components/Switch/style.ts
- src/helpers/color.ts
- src/helpers/index.ts
> Add switch component

- __tests__/components/Switch/Switch.spec.tsx
- src/components/Switch/style.ts
The Switch component was fixed on Parent element scroll
* Why is this change required? 
Design bug for Switch
* What problem does it solve?
Fixed the design for Switch
* Go over all the following points, and put an `x` in all the boxes that apply.
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
> hotfix: Fix switch component bug on parent scroll

- __tests__/components/Rating/Rating.spec.tsx
- src/components/Rating/Rating.stories.tsx
- src/components/Rating/Rating.tsx
- src/components/Rating/index.ts
- src/components/Rating/style.ts
- src/index.ts
Implement Rating component
* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to.
* see how your change affects other areas of the code, etc.
* Go over all the following points, and put an `x` in all the boxes that apply.
* If you're unsure about any of these, don't hesitate to ask. We're here to help!
> :fire: Implement Rating component

- __tests__/components/Rating/Rating.spec.tsx
- src/components/Rating/Rating.stories.tsx
- src/components/Rating/Rating.tsx
- src/components/Rating/style.ts
Add space in between rating elements
* This project only accepts pull requests related to open issues.
* If suggesting a new feature or change, please discuss it in an issue first.
* If fixing a bug, there should be an issue describing it with steps to reproduce.
* Please link to the issue here: [Create Issue](https://github.com/sha-el/sha-el-design/issues/new)
* Why is this change required? 
* What problem does it solve?
* Please describe in detail how you tested your changes.
* Include details of your testing environment, and the tests you ran to.
* see how your change affects other areas of the code, etc.
* Go over all the following points, and put an `x` in all the boxes that apply.
* If you're …
> hotfix: Add space in between rating elements
